### ISSUE TITLE
cpm fails to install Keywork::Declare bit cpanm succeds

### ISSUE THREAD

**Issue by patrickas** [skaji/cpm#206] opened 2021-08-19 09:54 UTC
When I try to install Data::Dx using cpm it fails for Keywork::Declare

$ sudo cpm install --show-build-log-on-failure -g Data::DX
.....
2021-08-19T09:49:03,42645,Data-Dx-0.000010| Found dependencies: Keyword::Declare (0.001003)
2021-08-19T09:49:03,42650,Keyword::Declare| Resolved Keyword::Declare (0.001003) -> https://cpan.metacpan.org/authors/id/D/DC/DCONWAY/Keyword-Declare-0.001017.tar.gz from MetaDB
2021-08-19T09:49:03,42650,Keyword-Declare-0.001017| Using cache /root/.perl-cpm/cache/authors/id/D/DC/DCONWAY/Keyword-Declare-0.001017.tar.gz
2021-08-19T09:49:03,42650,Keyword-Declare-0.001017| Unpacking Keyword-Declare-0.001017.tar.gz
2021-08-19T09:49:03,42650,Keyword-Declare-0.001017| Configuring distribution
2021-08-19T09:49:03,42650,Keyword-Declare-0.001017| Executing /usr/bin/perl Makefile.PL
2021-08-19T09:49:04,42650,Keyword-Declare-0.001017| Warning: prerequisite Keyword::Simple 0 not found.
2021-08-19T09:49:04,42650,Keyword-Declare-0.001017| Checking if your kit is complete...
2021-08-19T09:49:04,42650,Keyword-Declare-0.001017| Looks good
2021-08-19T09:49:04,42650,Keyword-Declare-0.001017| Generating a Unix-style Makefile
2021-08-19T09:49:04,42650,Keyword-Declare-0.001017| Writing Makefile for Keyword::Declare
2021-08-19T09:49:04,42650,Keyword-Declare-0.001017| Writing MYMETA.yml and MYMETA.json
2021-08-19T09:49:04,42645,Keyword-Declare-0.001017| Distribution provides: Keyword::Declare (0.001017), Keyword::Declare::Arg (0.001017), Keyword::Simple (0.001017)
2021-08-19T09:49:04,42645,Data-Dx-0.000010| Detected circular dependencies Data-Dx-0.000010 -> Keyword-Declare-0.001017 -> Keyword-Declare-0.001017
2021-08-19T09:49:04,42645,Data-Dx-0.000010| Failed to install distribution
2021-08-19T09:49:04,42645,Keyword-Declare-0.001017| Detected circular dependencies Keyword-Declare-0.001017 -> Keyword-Declare-0.001017
2021-08-19T09:49:04,42645,Keyword-Declare-0.001017| Failed to install distribution
ubuntu@invigo-dev-1:/data/arachne

Doing the same with cpan minus works

$ sudo cpanm Data::Dx
--> Working on Data::Dx
Fetching http://www.cpan.org/authors/id/D/DC/DCONWAY/Data-Dx-0.000010.tar.gz ... OK
Configuring Data-Dx-0.000010 ... OK
==> Found dependencies: Keyword::Declare
--> Working on Keyword::Declare
Fetching http://www.cpan.org/authors/id/D/DC/DCONWAY/Keyword-Declare-0.001017.tar.gz ... OK
Configuring Keyword-Declare-0.001017 ... OK
==> Found dependencies: Keyword::Simple
--> Working on Keyword::Simple
Fetching http://www.cpan.org/authors/id/M/MA/MAUKE/Keyword-Simple-0.04.tar.gz ... OK
Configuring Keyword-Simple-0.04 ... OK
Building and testing Keyword-Simple-0.04 ... OK
Successfully installed Keyword-Simple-0.04
Building and testing Keyword-Declare-0.001017 ... OK
Successfully installed Keyword-Declare-0.001017
Building and testing Data-Dx-0.000010 ... OK
Successfully installed Data-Dx-0.000010
3 distributions installed

**Comment by skaji** [comment] 2021-08-19 10:05
Keyword-Declare-0.001017 requires Keyword::Simple, while it provides Keyword::Simple.
https://metacpan.org/release/DCONWAY/Keyword-Declare-0.001017/source/META.json#L38
https://metacpan.org/release/DCONWAY/Keyword-Declare-0.001017/source/lib/Keyword/Declare.pm#L338

**Comment by skaji** [comment] 2021-08-19 10:45
duplicate of https://github.com/skaji/cpm/issues/194

**Closed by skaji** 2021-08-19 10:46 UTC

**Comment by skaji** [comment] 2021-08-19 13:49
https://rt.cpan.org/Public/Bug/Display.html?id=138876
